/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    // Apply the maven-publish plugin to add support for publishing to Maven repositories.
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.kotlin.reflect)
    implementation(libs.kotlinx.coroutines.core)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            groupId = "org.holance"
            artifactId = "ktbus"
            version = project.version.toString()
            pom {
                name = "KtBus"
                description = "An event bus implementation based on Kotlin Sharedflow."
                url = "https://github.com/holance/ktbus"
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://github.com/holance/ktbus/blob/publish-maven-package/LICENSE"
                    }
                }
                developers {
                    developer {
                        id = "holance"
                        name = "holance"
                        email = "holance.app@gmail.com"
                    }
                }
                scm {
                    connection = "scm:git:git://github.com/holance/ktbus.git"
                    developerConnection = "scm:git:ssh://github.com/holance/ktbus.git"
                    url = "https://github.com/holance/ktbus"
                }
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/holance/ktbus")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.token") as String? ?: System.getenv("TOKEN")
            }
        }
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.11.3")
        }
    }
}

tasks.jar {
    archiveFileName = "ktbus.jar" // Replace with your desired filename.
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(11) // Specify your target JVM version
}

version = System.getenv("VERSION") ?: "unspecified"

// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(11)
//    }
//}
