name: Build and Test

on:
  push:
    branches: [ main, develop* ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main, develop* ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'
          
      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          useConfigFile: true
          configFilePath: gitversion.yml

      - name: Set version in Gradle build file
        run: ./gradlew -Pversion=${{ steps.version_step.outputs.SemVer }}

      - name: Build with Gradle
        run: ./gradlew :lib:assemble

      - name: Run tests
        run: ./gradlew :lib:test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ steps.version_step.outputs.SemVer }}
          path: |
            lib/build/libs/*.jar
