name: Build and Test

on:
  push:
    branches: [ main, develop* ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main, develop* ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Generate version information
        id: gitversion
        run: gitversion /output json /output buildserver

      - name: Set version in Gradle build file
        run: ./gradlew -Pversion=$(gitversion | jq -r '.SemVer')

      - name: Build with Gradle
        run: ./gradlew :lib:assemble

      - name: Run tests
        run: ./gradlew :lib:test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-$(gitversion | jq -r '.SemVer')
          path: |
            lib/build/libs/*.jar
