name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :lib:assemble

      - name: Run tests
        run: ./gradlew :lib:test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: library-artifacts
          path: lib/build/libs  # Adjust the path if necessary